=== angeldelblanco/eCharacter/assets/XSD/family.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="family">
		<xs:complexType>
			<xs:sequence>
				<!--This element contains all information about 
			the family. License and URL are optional 
			elements.-->
				<xs:element name="metadata">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="license" type="licenseType" minOccurs="0" maxOccurs="1"/>
							<xs:element name="name" type="xs:string"/>
							<xs:element name="abstract" type="xs:string"/>
							<xs:element name="description" type="xs:string"/>
							<xs:element name="author" type="xs:string"/>
							<xs:element name="URL" type="xs:string" minOccurs="0" maxOccurs="1"/>
							<!--Internationalization files 
							should be in this path-->
							<xs:element name="languagesPath" type="xs:string"/>
							<xs:element name="iconPath" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<!-- This element contains information about the GUI. 
					The order in which stages are defined, defines 
					the order in which show it -->
				<xs:element name="stages">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="scaleStage" type="scaleStageType" minOccurs="0" maxOccurs="10"/>
							<xs:element name="multiStage" type="multiStageType" minOccurs="0" maxOccurs="10"/>
							<!-- Animation stage is 
							obligatory.-->
							<xs:element name="animationStage" type="animationStageType"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="modelsRef">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="modelRef" type="modelRefType" minOccurs="1" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="licenseType">
		<xs:sequence>
			<xs:element name="title" type="xs:string"/>
			<xs:element name="terms" type="xs:string"/>
			<xs:element name="URL" type="xs:string" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="multiStageType">
		<xs:sequence>
			<!-- If iconPath exists, it will be displayed in the top 
			banner instead of stageLabel. -->
			<xs:element name="iconPath" type="xs:string"/>
			<xs:element name="subStage" type="subStageType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="stageLabel" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="subStageType">
		<xs:attribute name="subStageType" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="meshSubStage"/>
					<xs:enumeration value="textureSubStage"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="subStageLabel" type="xs:string" use="required"/>
		<xs:attribute name="idPanel" type="xs:ID" use="required"/>
		<xs:attribute name="multiselection" type="xs:boolean" use="optional"/>
		<!--If multiselection is true, users would be able to select many 
		textures or submeshes in the same substage.-->
	</xs:complexType>
	<xs:complexType name="scaleStageType">
		<xs:sequence>
			<!-- If iconPath exists, it will be displayed in the top 
			banner instead of stageLabel. -->
			<xs:element name="iconPath" type="xs:string"/>
			<xs:element name="boneController" minOccurs="1" maxOccurs="15">
				<xs:complexType>
					<xs:attribute name="controllerLabel" type="xs:string" use="required"/>
					<xs:attribute name="idController" type="xs:ID" use="required"/>
					<xs:attribute name="level" type="xs:integer" use="required"/>
					<!-- Level allow us make a tree structure to 
					organize the controllers. The highest level is 
					0 and it increase in lower levels.-->
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="stageLabel" type="xs:string" use="required"/>
		<xs:attribute name="idPanel" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:complexType name="animationStageType">
		<xs:sequence>
			<xs:element name="fps" type="fpsType" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element name="camera" type="cameraType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="stageLabel" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="fpsType">
		<xs:attribute name="qualityLabel" type="xs:string" use="required"/>
		<xs:attribute name="fpsValue" type="xs:integer" use="required"/>
	</xs:complexType>
	<xs:complexType name="cameraType">
		<xs:sequence>
			<xs:element name="upAxis" type="vectorType"/>
			<xs:element name="location" type="vectorType"/>
			<xs:element name="direction" type="vectorType"/>
		</xs:sequence>
		<xs:attribute name="cameraLabel" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="vectorType">
		<xs:attribute name="valueX" type="xs:float" use="required"/>
		<xs:attribute name="valueY" type="xs:float" use="required"/>
		<xs:attribute name="valueZ" type="xs:float" use="required"/>
	</xs:complexType>
	<xs:complexType name="modelRefType">
		<xs:sequence>
			<xs:element name="modelLabel" type="xs:ID"/>
			<xs:element name="iconPath" type="xs:string"/>
			<xs:element name="modelPath" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== angeldelblanco/eCharacter/assets/XML Configuration/families/eAdventure.xml
<?xml version="1.0" encoding="UTF-8"?>
<family xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../family.xsd">
	<metadata>
		<name>idNameFamily</name>
		<description>idDescriptionFamily</description>
		<author>idAuthor</author>
		<languagesPath>assets/Locale/eAdventure</languagesPath>
		<iconPath>assets/Interface/Icons/eAdventure/IconoeAdventure.png</iconPath>
	</metadata>
	<stages>
		<scaleStage stageLabel="idMultiStageLabel1" idPanel="ScalePanel">
			<iconPath>assets/Interface/Icons/eAdventure/IconosBarraSuperior_0000_Complexion.png</iconPath>
			<boneController controllerLabel="idBoneControler1" idController="torsoHeadArms" level="0"/>
			<boneController controllerLabel="idBoneControler2" idController="head" level="1"/>
			<boneController controllerLabel="idBoneControler3" idController="arms" level="1"/>
			<boneController controllerLabel="idBoneControler4" idController="leftArm" level="2"/>
			<boneController controllerLabel="idBoneControler5" idController="leftHand" level="3"/>
			<boneController controllerLabel="idBoneControler6" idController="rightArm" level="2"/>
			<boneController controllerLabel="idBoneControler7" idController="rightHand" level="3"/>
			<boneController controllerLabel="idBoneControler8" idController="legs" level="0"/>
			<boneController controllerLabel="idBoneControler9" idController="leftLeg" level="1"/>
			<boneController controllerLabel="idBoneControler10" idController="leftFoot" level="2"/>
			<boneController controllerLabel="idBoneControler11" idController="rightLeg" level="1"/>		
			<boneController controllerLabel="idBoneControler12" idController="rightFoot" level="2"/>			
		</scaleStage>
		<multiStage stageLabel="idMultiStageLabel2">
			<iconPath>assets/Interface/Icons/eAdventure/IconosBarraSuperior_0001_Piel.png</iconPath>
			<subStage subStageType="textureSubStage" subStageLabel="idTextureSubStageLabel1" idPanel="skinsPanel" multiselection="false"/>
		</multiStage>
		<multiStage stageLabel="idMultiStageLabel3">
			<iconPath>assets/Interface/Icons/eAdventure/IconosBarraSuperior_0002_Ojos.png</iconPath>
			<subStage subStageType="textureSubStage" subStageLabel="idTextureSubStageLabel2" idPanel="eyesPanel" multiselection="true"/>
			<subStage subStageType="textureSubStage" subStageLabel="idTextureSubStageLabel3" idPanel="eyebrowsPanel" multiselection="true"/>
		</multiStage>
		<multiStage stageLabel="idMultiStageLabel4">
			<iconPath>assets/Interface/Icons/eAdventure/IconosBarraSuperior_0003_Camiseta.png</iconPath>
			<subStage subStageType="textureSubStage" subStageLabel="idTextureSubStageLabel4" idPanel="tshirtsPanel" multiselection="false"/>
		</multiStage>
		<multiStage stageLabel="idMultiStageLabel5">
			<iconPath>assets/Interface/Icons/eAdventure/IconosBarraSuperior_0004_Pantalones.png</iconPath>
			<subStage subStageType="textureSubStage" subStageLabel="idTextureSubStageLabel5" idPanel="trousersPanel" multiselection="false"/>
		</multiStage>		
		<multiStage stageLabel="idMultiStageLabel6">
			<iconPath>assets/Interface/Icons/eAdventure/IconosBarraSuperior_0005_Calzado.png</iconPath>
			<subStage subStageType="textureSubStage" subStageLabel="idTextureSubStageLabel6" idPanel="shoesPanel" multiselection="false"/>
			<subStage subStageType="textureSubStage" subStageLabel="idTextureSubStageLabel7" idPanel="socksPanel" multiselection="true"/>
		</multiStage>
		<multiStage stageLabel="idMultiStageLabel7">
			<iconPath>assets/Interface/Icons/eAdventure/IconosBarraSuperior_0006_Pelo.png</iconPath>
			<subStage subStageType="meshSubStage" subStageLabel="idTextureSubStageLabel8" idPanel="hairsPanel" multiselection="false"/>
		</multiStage>
		<multiStage stageLabel="idMultiStageLabel8">
			<iconPath>assets/Interface/Icons/eAdventure/IconosBarraSuperior_0007_Accesorios.png</iconPath>
			<subStage subStageType="textureSubStage" subStageLabel="idTextureSubStageLabel9" idPanel="facePanel" multiselection="true"/>
			<subStage subStageType="textureSubStage" subStageLabel="idTextureSubStageLabel10" idPanel="accesoriesFacePanel" multiselection="true"/>
			<subStage subStageType="textureSubStage" subStageLabel="idTextureSubStageLabel11" idPanel="otherAccesoriesPanel" multiselection="true"/>
		</multiStage>
		<animationStage stageLabel="idAnimationStageLabel1">
			<!-- Dar valores. Los que hay son aleatorios -->
			<fps qualityLabel="idQualityLabel1" fpsValue="24"/>
			<fps qualityLabel="idQualityLabel2" fpsValue="12"/>
			<fps qualityLabel="idQualityLabel3" fpsValue="6"/>
			<camera cameraLabel="idCameraLabel1">
				<upAxis valueX="0.0" valueY="1.0" valueZ="0.0"/>
				<location valueX="0.0" valueY="0.0" valueZ="10.0"/>
				<direction valueX="0.0" valueY="0.0" valueZ="-1.0"/>
			</camera>
			<camera cameraLabel="idCameraLabel2">
				<upAxis valueX="0.0" valueY="1.0" valueZ="0.0"/>
				<location valueX="-3.0" valueY="5.0" valueZ="10.0"/>
				<direction valueX="0.0" valueY="0.0" valueZ="-1.0"/>
			</camera>
		</animationStage>
	</stages>
	<modelsRef>
		<modelRef>
			<modelLabel>idModelLabel1</modelLabel>
			<iconPath>assets/Interface/Icons/eAdventure/eAdventure-chico.png</iconPath>
			<modelPath>assets/XML Configuration/models/eAdventure/Man.xml</modelPath>
		</modelRef>
		<modelRef>
			<modelLabel>idModelLabel2</modelLabel>
			<iconPath>assets/Interface/Icons/eAdventure/eAdventure-chica.png</iconPath>
			<modelPath>assets/XML Configuration/models/eAdventure/Woman.xml</modelPath>
		</modelRef>	
		<modelRef>
			<modelLabel>idModelLabel3</modelLabel>
			<iconPath>assets/Interface/Icons/eAdventure/young_boy.png</iconPath>
			<modelPath>assets/XML Configuration/models/eAdventure/YoungBoy.xml</modelPath>
		</modelRef>
		<modelRef>
			<modelLabel>idModelLabel4</modelLabel>
			<iconPath>assets/Interface/Icons/eAdventure/young_girl.png</iconPath>
			<modelPath>assets/XML Configuration/models/eAdventure/YoungWoman.xml</modelPath>
		</modelRef>
	</modelsRef>
</family>

=== angeldelblanco/eCharacter/assets/XML Configuration/families/Medieval.xml
<?xml version="1.0" encoding="UTF-8"?>
<family xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../family.xsd">
	<metadata>
		<name>idNameFamily</name>
		<description>idDescriptionFamily</description>
		<author>idAuthor</author>
		<languagesPath>assets\Locale\Medieval</languagesPath>
		<iconPath></iconPath>
	</metadata>
	<stages>
	<!-- Revisar que controladores poner -->
		<scaleStage stageLabel="idMultiStageLabel1" idPanel="ScalePanel">
			<boneController controllerLabel="idBoneControler1" idController="head"/>
			<boneController controllerLabel="idBoneControler2" idController="arms"/>
			<boneController controllerLabel="idBoneControler3" idController="hands"/>
			<boneController controllerLabel="idBoneControler4" idController="legs"/>
			<boneController controllerLabel="idBoneControler5" idController="feet"/>
		</scaleStage>
		<multiStage stageLabel="idMultiStageLabel2">
			<subStage subStageType="textureSubStage" subStageLabel="idTextureSubStageLabel1" idPanel="skinsPanel" multiselection="false"/>
		</multiStage>
		<multiStage stageLabel="idMultiStageLabel3">
			<subStage subStageType="textureSubStage" subStageLabel="idTextureSubStageLabel2" idPanel="hairsPanel" multiselection="false"/>
		</multiStage>
		<multiStage stageLabel="idMultiStageLabel4">
			<subStage subStageType="textureSubStage" subStageLabel="idTextureSubStageLabel3" idPanel="eyesPanel" multiselection="false"/>
		</multiStage>
		<multiStage stageLabel="idMultiStageLabel5">
			<subStage subStageType="textureSubStage" subStageLabel="idTextureSubStageLabel4" idPanel="shirtsPanel" multiselection="true"/>
			<subStage subStageType="textureSubStage" subStageLabel="idTextureSubStageLabel5" idPanel="trousersPanel" multiselection="true"/>
		</multiStage>
		<multiStage stageLabel="idMultiStageLabel6">
			<subStage subStageType="textureSubStage" subStageLabel="idTextureSubStageLabel6" idPanel="shoesPanel" multiselection="false"/>
		</multiStage>
		<multiStage stageLabel="idMultiStageLabel7">
			<subStage subStageType="textureSubStage" subStageLabel="idTextureSubStageLabel7" idPanel="accesoriesPanel" multiselection="true"/>
		</multiStage>
		<!-- Revisar la etapa de animaciÃ³n -->
		<animationStage stageLabel="idAnimationStageLabel1">
			<!-- Dar valores. Los que hay son aleatorios -->
			<fps qualityLabel="idQualityLabel1" fpsValue="3"/>
			<fps qualityLabel="idQualityLabel2" fpsValue="2"/>
			<fps qualityLabel="idQualityLabel3" fpsValue="1"/>
			<camera cameraLabel="idCameraLabel1">
				<upAxis valueX="0.0" valueY="1.0" valueZ="0.0"/>
				<location valueX="0.0" valueY="0.0" valueZ="10.0"/>
				<direction valueX="0.0" valueY="0.0" valueZ="-1.0"/>
			</camera>
			<camera cameraLabel="idCameraLabel2">
				<upAxis valueX="0.0" valueY="1.0" valueZ="0.0"/>
				<location valueX="-3.0" valueY="5.0" valueZ="10.0"/>
				<direction valueX="0.0" valueY="0.0" valueZ="-1.0"/>
			</camera>
		</animationStage>
	</stages>
	<modelsRef>
		<modelRef>
			<modelLabel>idModelLabel1</modelLabel>	
			<iconPath>assets\Interface\Icons\Medieval\IconMale.png</iconPath>
			<modelPath>assets\XML Configuration\models\Medieval\Male.xml</modelPath>
		</modelRef>
		<modelRef>
			<modelLabel>idModelLabel2</modelLabel>
			<iconPath>assets\Interface\Icons\Medieval\IconFemale.png</iconPath>
			<modelPath>assets\XML Configuration\models\Medieval\Female.xml</modelPath>
		</modelRef>	
	</modelsRef>
</family>
