=== angeldelblanco/eCharacter/assets/Locale/language.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="metadata">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="string" minOccurs="1" maxOccurs="unbounded" type="stringType"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="stringType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="id" type="xs:ID" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	  </xs:complexType>
</xs:schema>

=== angeldelblanco/eCharacter/assets/Locale/Cubix Studio/Female/fr_FR.xml
<?xml version="1.0" encoding="UTF-8"?>
<metadata language="fr_FR" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../language.xsd">
	<string id="idPhysicalBuildLabel1">Moyenne</string>
        <string id="idPhysicalBuildLabel2">Haut</string>
	<string id="idPhysicalBuildLabel3">Bas</string>
	<string id="idTextPielCasual">Peau casual</string>
	<string id="idTextPielMedieval">Peau médiéval</string>
	<string id="idTextPeloCasual">Cheveaux casual</string>
	<string id="idTextPeloMedieval">Cheveaus médiéval</string>
	<string id="idTextOjosCasual">Yeaux casual</string>
	<string id="idTextOjosMedieval">Yeaux médiéval</string>
	<string id="idTextCamisetaCasual">Camiseta casual</string>
	<string id="idTextFaldaCasual">Jupe casual</string>
	<string id="idTextVestidoMedieval">Robe médiéval</string>
	<string id="idTextZapatosCasual">Chaussures casual</string>
	<string id="idTextZapatosMedieval">Chaussures médiéval</string>
	<string id="idTextRopaInterior">Sous-vêtements</string>
	<string id="idTextCinta">Bande à tête</string>
	<string id="idTextLabiosCasual">Lèvres casual</string>
	<string id="idTextLabiosMedieval">Lèvres médiéval</string>
</metadata>

=== angeldelblanco/eCharacter/assets/Locale/Humans/en_UK.xml
<?xml version="1.0" encoding="UTF-8"?>
<metadata language="en_UK" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../language.xsd">
	<string id="idNameFamily">Humans</string>
	<string id="idDescriptionFamily">This family has composed by four humans: a man, a woman, a young boy and a young girl.</string>
	<string id="idMultiStageLabel1">Scale</string>
	<string id="idBoneControler1">Head</string>
	<string id="idBoneControler2">Torso</string>
	<string id="idBoneControler3">Left arm</string>
	<string id="idBoneControler4">Right arm</string>
	<string id="idBoneControler5">Left hand</string>
	<string id="idBoneControler6">Right hand</string>
	<string id="idBoneControler7">Left leg</string>
	<string id="idBoneControler8">Right leg</string>
	<string id="idBoneControler9">Left foot</string>
	<string id="idBoneControler10">Right foot</string>
	<string id="idMultiStageLabel2">Skin</string>
	<string id="idTextureSubStageLabel1">Skins</string>
	<string id="idMultiStageLabel3">Eyes</string>
	<string id="idTextureSubStageLabel2">Eyes</string>
	<string id="idTextureSubStageLabel3">Eyebrows and Eyelashes</string>
	<string id="idMultiStageLabel4">T-Shirts</string>
	<string id="idTextureSubStageLabel4">T-Shirts</string>
	<string id="idMultiStageLabel5">Trousers</string>
	<string id="idTextureSubStageLabel5">Trousers</string>
	<string id="idMultiStageLabel6">Shoes</string>
	<string id="idTextureSubStageLabel6">Shoes</string>
	<string id="idTextureSubStageLabel7">Socks</string>
	<string id="idMultiStageLabel7">Hair</string>
	<string id="idTextureSubStageLabel8">Hairs</string>
	<string id="idMultiStageLabel8">Accesories</string>
	<string id="idTextureSubStageLabel9">Face</string>
	<string id="idTextureSubStageLabel10">Accesories face</string>
	<string id="idTextureSubStageLabel11">Other accesories</string>
	<string id="idAnimationStageLabel1">Export</string>
	<string id="idQualityLabel1">High</string>
	<string id="idQualityLabel2">Medium</string>
	<string id="idQualityLabel3">Low</string>
	<string id="idCameraLabel1">Front</string>
	<string id="idCameraLabel2">2D</string>
	<string id="idModelLabel1">Boy</string>
	<string id="idModelLabel2">Girl</string>
	<string id="idModelLabel3">Young boy</string>
	<string id="idModelLabel4">Young girl</string>
</metadata>

=== angeldelblanco/eCharacter/assets/Locale/Gui/fr_FR.xml
<?xml version="1.0" encoding="UTF-8"?>
<metadata language="fr_FR" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="language.xsd">
	<string id="language">assets/Locale/Flags/France.png</string>
	<string id="idDescription">Bienvenue au configurateur des personages pour eAdventure. Avec cet configurateur des personages vous pouvez crèer votre avatar pour jouer aux jeux dans la platforme eAdventure.</string>
	<string id="idStart">Démarrer</string>
	<string id="idQuit">Sortir</string>
	<string id="idLanguage">Langue</string>
	<string id="idChoose">Choisi ton modéle</string>
	<string id="idFamily">Choisi la famille:</string>
	<string id="idPrevious">Précédent</string>
	<string id="idNext">Suivant</string>
	<string id="idFinish">Finaliser</string>
	<string id="idColor">Coleur</string>
	<string id="idQuality">Qualité</string>
	<string id="idCamera">Caméra</string>
	<string id="idAnimations">Animations</string>
        <string id="idPreview">Voir</string>
	<string id="idPopup1">Est-ce que vous voulez retoucher le modéle ou contiuner l'exportation?</string>
	<string id="idPopup2">Est-ce que vous voulez créer un nouveau modéle?</string>
	<string id="idPopupButton1">Retoucher</string>
	<string id="idPopupButton2">Exporter</string>
	<string id="idPopupButton3">Oui</string>
	<string id="idPopupButton4">Non</string>
        <string id="idBase">Base</string>
        <string id="idDetails">Détails</string>
	<string id="idRed">Rouge</string>
	<string id="idGreen">Vert</string>
	<string id="idBlue">Bleu</string>
	<string id="idAcept">Accepter</string>
	<string id="idCancel">Annuler</string>
	<string id="idBasic">De base</string>
	<string id="idCustom">Personnalisée</string>
	<string id="idAll">Tous</string>
	<string id="idNothing">Aucun</string>
	<string id="idDescriptionFamily">Description</string>
	<string id="idAuthor">Author</string>
	<string id="idUrl">Url</string>
	<string id="idHeader">Sélectionnez une famille, puis le modèle de base pour commencer</string>
	<string id="idSubHeader">Bienvenue à eCharacter, les caractères de eAdventure configurateur. Pour en savoir plus sur le projet, cliquez</string>
	<string id="idHere">ici</string>
	<string id="idWelcome">Bienvenue</string>
	<string id="ideCharacter">Chaîne caractères configurateur</string>
	<string id="idPopupLanguage">S'il vous plaît choisir la langue que vous préférez utiliser la liste</string>
</metadata>

=== angeldelblanco/eCharacter/assets/Locale/Gui/es_ES.xml
<?xml version="1.0" encoding="UTF-8"?>
<metadata language="es_ES" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./language.xsd">
	<string id="language">assets/Locale/Flags/Spain.png</string>
	<string id="idDescription">Bienvenido al configurador de personajes para eAdventure. Con este configurador de personajes podrás crear tu avatar para jugar a los juegos de la plataforma eAdventure.</string>
	<string id="idStart">Inicio</string>
	<string id="idQuit">Salir</string>
	<string id="idLanguage">Idioma</string>
	<string id="idChoose">Elige tu modelo</string>
	<string id="idFamily">Elige la familia:</string>
	<string id="idPrevious">Anterior</string>
	<string id="idNext">Siguiente</string>
	<string id="idFinish">Finalizar</string>
	<string id="idColor">Color</string>
	<string id="idQuality">Calidad</string>
	<string id="idCamera">Cámara</string>
	<string id="idAnimations">Animaciones</string>
        <string id="idPreview">Ver</string>
	<string id="idPopup1">¿Quiere retocar el modelo o continuar con la exportación?</string>
	<string id="idPopup2">¿Quiere generar un nuevo modelo?</string>
	<string id="idPopupButton1">Retocar</string>
	<string id="idPopupButton2">Exportar</string>
	<string id="idPopupButton3">Si</string>
	<string id="idPopupButton4">No</string>
        <string id="idBase">Base</string>
        <string id="idDetails">Detalles</string>
	<string id="idRed">Rojo</string>
	<string id="idGreen">Verde</string>
	<string id="idBlue">Azul</string>
	<string id="idAcept">Aceptar</string>
	<string id="idCancel">Cancelar</string>
	<string id="idBasic">Basico</string>
	<string id="idCustom">Avanzado</string>
	<string id="idAll">Todas</string>
	<string id="idNothing">Ninguna</string>
	<string id="idDescriptionFamily">Descripción</string>
	<string id="idAuthor">Autor</string>
	<string id="idUrl">Url</string>
	<string id="idHeader">Selecciona una familia y luego el modelo base para comenzar</string>
	<string id="idSubHeader">Bienvenido a eCharacter, el configurador de personajes de eAdventure. Para conocer más detalles sobre el proyecto pulse</string>
	<string id="idHere">aquí</string>
	<string id="idWelcome">Bienvenido a</string>
	<string id="ideCharacter">El configurador de personajes</string>
	<string id="idPopupLanguage">Por favor, seleccione el idioma de la lista que prefiera utilizar</string>
	<string id="idDownload">Descargar</string>
	<string id="idRepoText">Descarga las familias que más te gusten</string>
</metadata>

=== angeldelblanco/eCharacter/assets/Locale/Cubix Studio/Female/en_UK.xml
<?xml version="1.0" encoding="UTF-8"?>
<metadata language="en_UK" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../language.xsd">
	<string id="idPhysicalBuildLabel1">Medium-Built</string>
        <string id="idPhysicalBuildLabel2">Tall</string>
        <string id="idPhysicalBuildLabel3">Small</string>
	<string id="idTextPielCasual">Casual skin</string>
	<string id="idTextPielMedieval">Medieval skin</string>
	<string id="idTextPeloCasual">Casual hair</string>
	<string id="idTextPeloMedieval">Medieval hair</string>
	<string id="idTextOjosCasual">Casual eyes</string>
	<string id="idTextOjosMedieval">Medieval eyes</string>
	<string id="idTextCamisetaCasual">Casual t-shirt</string>
	<string id="idTextFaldaCasual">Casual skirt</string>
	<string id="idTextVestidoMedieval">Medieval dress</string>
	<string id="idTextZapatosCasual">Casual shoes</string>
	<string id="idTextZapatosMedieval">Medieval shoes</string>
	<string id="idTextRopaInterior">Underwear</string>
	<string id="idTextCinta">Headband</string>
	<string id="idTextLabiosCasual">Casual lips</string>
	<string id="idTextLabiosMedieval">Medieval lips</string>
</metadata>

=== angeldelblanco/eCharacter/assets/Locale/en_UK.xml
<?xml version="1.0" encoding="UTF-8"?>
<metadata language="en_UK" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="language.xsd">
	<string id="idDescription">Welcome to eAdventure characters configurator. This configurator can create your avatar to play platform games eAdventure.</string>
	<string id="idAuthor">Alex,Sergio and David</string>
	<string id="idStart">Start</string>
	<string id="idQuit">Quit</string>
	<string id="idLanguage">Language</string>
	<string id="idChoose">Choose your model</string>
	<string id="idFamily">Choose the family:</string>
	<string id="idPrevious">Previous</string>
	<string id="idNext">Next</string>
	<string id="idFinish">Finish</string>
	<string id="idColor">Color</string>
	<string id="idQuality">Quality</string>
	<string id="idCamera">Camera</string>
	<string id="idPreview">Animations</string>
	<string id="idPopup1">Do you want to tweak the model, or go to the export stage?</string>
	<string id="idPopup2">Do you want to generate a new model?</string>
	<string id="idPopupButton1">Tweak model</string>
	<string id="idPopupButton2">Export</string>
	<string id="idPopupButton3">Yes</string>
	<string id="idPopupButton4">No</string>
</metadata>
