=== angeldelblanco/eCharacter/assets/Locale/language.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="metadata">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="string" minOccurs="1" maxOccurs="unbounded" type="stringType"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="stringType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="id" type="xs:ID" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	  </xs:complexType>
</xs:schema>

=== angeldelblanco/eCharacter/assets/Locale/eAdventure/Woman/fr_FR.xml
<?xml version="1.0" encoding="UTF-8"?>
<metadata language="fr_FR" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../language.xsd">
	<string id="idPhysicalBuildLabel1">Corpulence moyenne</string>
	<string id="idPhysicalBuildLabel2">Gros</string>
	<string id="idPhysicalBuildLabel3">Mince</string>
	<string id="idPhysicalBuildLabel4">Haut</string>
	<string id="idPhysicalBuildLabel5">Bas</string>
	<string id="idTextPielBlanca">Peau blanche</string>
	<string id="idTextPielNegra">Peau noire</string>
	<string id="idTextPielAmarillaOscura">Peau jaune foncé</string>
	<string id="idTextPielAmarillaClara">Peau jaune clair</string>
	<string id="idTextPielRoja">Redskin</string>
	<string id="idTextBlancoOjos">Sclérotique</string>
	<string id="idTextOjos">Yeux</string>
	<string id="idTextCejas1">Sourcils minces</string>
	<string id="idTextCejas2">Sourcils gras</string>
	<string id="idTextPestanas">Onglets</string>
	<string id="idTextCamisetaSinMangas">Tee-shirt sans manches</string>
	<string id="idTextCamiseta">Tee-shirt</string>
	<string id="idTextCamisetaTirantes">Tee-shirt de bretelles</string>
	<string id="idTextTop">Top</string>
	<string id="idTextPantalonCorto">Short</string>
	<string id="idTextPantalonLargo">Long pantalon</string>
	<string id="idTextZapatos">Chaussures</string>
	<string id="idTextMedias">Moyennes</string>
	<string id="idTextColorete">Fards à joues</string>
	<string id="idTextSombraOjos">Fard à paupières</string>
	<string id="idTextLabios">Lèvres</string>
	<string id="idTextDientes">Dents</string>
	<string id="idTextLengua">Langue</string>
	<string id="idTextPendientes">Boucles d'oreille</string>
	<string id="idTextTiritaDcha">Droite grelotte</string>
	<string id="idTextTiritaIzq">Gauche grelotte</string>
	<string id="idTextPearcingBarbilla">Piercing dans le menton</string>
	<string id="idTextPearcingDcho">Piercing droit</string>
	<string id="idTextPearcingIzq">Piercing gauche</string>
	<string id="idTextCollar1">Collier</string>
	<string id="idTextCollar2">Collier</string>
	<string id="idTextLazoCuello">Boucle dans le cou</string>
	<string id="idTextMunequeras">Bracelets</string>
	<string id="idTextPulseraDcha">Poignet droit</string>
	<string id="idTextPulseraIzq">Poignet gauche</string>
	<string id="idTextPeloLong">Cheveux longs</string>
	<string id="idTextPeloOld">Vieux cheveux</string>
	<string id="idTextPeloPonyTail">Queue de cheval cheveux</string>
	<string id="idTextPeloShort">Cheveux courts</string>
</metadata>

=== angeldelblanco/eCharacter/assets/Locale/Cubix Studio/es_ES.xml
<?xml version="1.0" encoding="UTF-8"?>
<metadata language="es_ES" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../language.xsd">
	<string id="idNameFamily">Cubix Studio</string>
	<string id="idAbstractFamily">Hombre y mujer adultos de calidad media con estética realista.</string>
	<string id="idDescriptionFamily">Esta familia está compuesta por 2 humanos: un chico y una chica. Cada humano se puede vestir de casual o medieval.</string>
	<string id="idAuthor">Cubix Studio</string>
	<string id="idMultiStageLabel1">Escalado</string>
	<string id="idBoneControler1">Cabeza</string>
	<string id="idBoneControler2">Brazos</string>
	<string id="idBoneControler3">Manos</string>
	<string id="idBoneControler4">Piernas</string>
	<string id="idBoneControler5">Pies</string>
	<string id="idMultiStageLabel2">Piel</string>
	<string id="idTextureSubStageLabel1">Pieles</string>
	<string id="idMultiStageLabel3">Pelo</string>
	<string id="idTextureSubStageLabel2">Pelos</string>
	<string id="idMultiStageLabel4">Ojos</string>
	<string id="idTextureSubStageLabel3">Ojos</string>
	<string id="idMultiStageLabel5">Ropa</string>
	<string id="idTextureSubStageLabel4">Camisetas</string>
	<string id="idTextureSubStageLabel5">Pantalones o faldas</string>
	<string id="idMultiStageLabel6">Zapatos</string>
	<string id="idTextureSubStageLabel6">Zapatos</string>
	<string id="idMultiStageLabel7">Accesorios</string>
	<string id="idTextureSubStageLabel7">Accesorios</string>
	<string id="idAnimationStageLabel1">Exportación</string>
	<string id="idQualityLabel1">Alto</string>
	<string id="idQualityLabel2">Medio</string>
	<string id="idQualityLabel3">Bajo</string>
	<string id="idCameraLabel1">Frontal</string>
	<string id="idCameraLabel2">2D</string>
	<string id="idModelLabel1">Hombre</string>
	<string id="idModelLabel2">Mujer</string>
</metadata>

=== angeldelblanco/eCharacter/assets/Locale/Medieval/en_UK.xml
<?xml version="1.0" encoding="UTF-8"?>
<metadata language="en_UK" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../language.xsd">
	<string id="idNameFamily">Medieval</string>
	<string id="idDescriptionFamily">This family has composed by two humans: a man and a woman. Every human can dress casual or medieval.</string>
	<string id="idAuthor">???</string>
	<!-- Revisar los nombres de los bone controller -->
	<string id="idMultiStageLabel1">Scale</string>
	<string id="idBoneControler1">Head</string>
	<string id="idBoneControler2">Arms</string>
	<string id="idBoneControler3">Hands</string>
	<string id="idBoneControler4">Legs</string>
	<string id="idBoneControler5">Feet</string>
	<string id="idMultiStageLabel2">Skin</string>
	<string id="idTextureSubStageLabel1">Skins</string>
	<string id="idMultiStageLabel3">Hair</string>
	<string id="idTextureSubStageLabel2">Hairs</string>
	<string id="idMultiStageLabel4">Eyes</string>
	<string id="idTextureSubStageLabel3">Eyes</string>
	<string id="idMultiStageLabel5">Clothes</string>
	<string id="idTextureSubStageLabel4">Shirts</string>
	<string id="idTextureSubStageLabel5">Trousers or skirts</string>
	<string id="idMultiStageLabel6">Shoes</string>
	<string id="idTextureSubStageLabel6">Shoes</string>
	<string id="idMultiStageLabel7">Accessories</string>
	<string id="idTextureSubStageLabel7">Accessories</string>
	<string id="idAnimationStageLabel1">Export</string>
	<string id="idQualityLabel1">High</string>
	<string id="idQualityLabel2">Medium</string>
	<string id="idQualityLabel3">Low</string>
	<string id="idCameraLabel1">Front</string>
	<string id="idCameraLabel2">2D</string>
	<string id="idModelLabel1">Man</string>
	<string id="idModelLabel2">Woman</string>
</metadata>

=== angeldelblanco/eCharacter/assets/Locale/Cubix Studio/Male/es_ES.xml
<?xml version="1.0" encoding="UTF-8"?>
<metadata language="es_ES" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../language.xsd">
	<string id="idPhysicalBuildLabel1">Complexión media</string>
	<string id="idPhysicalBuildLabel2">Gordo</string>
	<string id="idPhysicalBuildLabel3">Delgado</string>
	<string id="idPhysicalBuildLabel4">Alto</string>
	<string id="idPhysicalBuildLabel5">Bajo</string>
	<string id="idTextPielCasual">Piel casual</string>
	<string id="idTextPielMedieval">Piel medieval</string>
	<string id="idTextPeloCasual">Pelo casual</string>
	<string id="idTextPeloMedieval">Pelo medieval</string>
	<string id="idTextOjosCasual">Ojos casual</string>
	<string id="idTextOjosMedieval">Ojos medieval</string>
	<string id="idTextCamisetaCasual">Camiseta casual</string>
	<string id="idTextCamisetaMedieval">Camiseta medieval</string>
	<string id="idTextPantalonCasual">Pantalón casual</string>
	<string id="idTextPantalonMedieval">Pantalón medieval</string>
	<string id="idTextZapatosCasual">Zapatos casual</string>
	<string id="idTextZapatosMedieval">Zapatos medieval</string>
	<string id="idTextGuantes">Guantes</string>
</metadata>

=== angeldelblanco/eCharacter/assets/Locale/Gui/en_UK.xml
<?xml version="1.0" encoding="UTF-8"?>
<metadata language="en_UK" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./language.xsd">
	<string id="language">assets/Locale/Flags/United_Kingdom.png</string>
	<string id="idDescription">Welcome to eAdventure characters configurator. This configurator can create your avatar to play platform games eAdventure.</string>
	<string id="idStart">Start</string>
	<string id="idQuit">Quit</string>
	<string id="idLanguage">Language</string>
	<string id="idChoose">Choose your model</string>
	<string id="idFamily">Choose the family:</string>
	<string id="idPrevious">Previous</string>
	<string id="idNext">Next</string>
	<string id="idFinish">Finish</string>
	<string id="idColor">Color</string>
	<string id="idQuality">Quality</string>
	<string id="idCamera">Camera</string>
	<string id="idAnimations">Animations</string>
        <string id="idPreview">Preview</string>
	<string id="idPopup1">Do you want to tweak the model, or go to the export stage?</string>
	<string id="idPopup2">Do you want to generate a new model?</string>
	<string id="idPopupButton1">Tweak model</string>
	<string id="idPopupButton2">Export</string>
	<string id="idPopupButton3">Yes</string>
	<string id="idPopupButton4">No</string>
        <string id="idBase">Base</string>
        <string id="idDetails">Details</string>
	<string id="idRed">Red</string>
	<string id="idGreen">Green</string>
	<string id="idBlue">Blue</string>
	<string id="idAcept">Acept</string>
	<string id="idCancel">Cancel</string>
	<string id="idBasic">Basic</string>
	<string id="idCustom">Custom</string>
	<string id="idAll">All</string>
	<string id="idNothing">Nothing</string>
	<string id="idDescriptionFamily">Description</string>
	<string id="idAuthor">Author</string>
	<string id="idUrl">Url</string>
</metadata>

=== angeldelblanco/eCharacter/assets/Locale/eAdventure/es_ES.xml
<?xml version="1.0" encoding="UTF-8"?>
<metadata language="es_ES" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../language.xsd">
	<string id="idNameFamily">eAdventure</string>
	<string id="idDescriptionFamily">Esta familia está compuesta por 2 humanos: un chico y una chica.</string>
	<string id="idAuthor">Alex,Sergio y David</string>
	<string id="idMultiStageLabel1">Escalado</string>
	<string id="idBoneControler1">Cabeza</string>
	<string id="idBoneControler2">Torso</string>
	<string id="idBoneControler3">Brazo izquierdo</string>
	<string id="idBoneControler4">Brazo derecho</string>
	<string id="idBoneControler5">Mano izquierda</string>
	<string id="idBoneControler6">Mano derecha</string>
	<string id="idBoneControler7">Pierna izquierda</string>
	<string id="idBoneControler8">Pierna derecha</string>
	<string id="idBoneControler9">Pie izquierdo</string>
	<string id="idBoneControler10">Pie derecho</string>
	<string id="idMultiStageLabel2">Piel</string>
	<string id="idTextureSubStageLabel1">Pieles</string>
	<string id="idMultiStageLabel3">Ojos</string>
	<string id="idTextureSubStageLabel2">Ojos</string>
	<string id="idTextureSubStageLabel3">Cejas y pestañas</string>
	<string id="idMultiStageLabel4">Camisetas</string>
	<string id="idTextureSubStageLabel4">Camisetas</string>
	<string id="idMultiStageLabel5">Pantalones</string>
	<string id="idTextureSubStageLabel5">Pantalones</string>
	<string id="idMultiStageLabel6">Zapatos</string>
	<string id="idTextureSubStageLabel6">Zapatos</string>
	<string id="idTextureSubStageLabel7">Calcetines</string>
	<string id="idMultiStageLabel7">Pelo</string>
	<string id="idTextureSubStageLabel8">Pelos</string>
	<string id="idMultiStageLabel8">Accesorios</string>
	<string id="idTextureSubStageLabel9">Cara</string>
	<string id="idTextureSubStageLabel10">Accesorios de la cara</string>
	<string id="idTextureSubStageLabel11">Otros accesorios</string>
	<string id="idAnimationStageLabel1">Exportación</string>
	<string id="idQualityLabel1">Alto</string>
	<string id="idQualityLabel2">Medio</string>
	<string id="idQualityLabel3">Bajo</string>
	<string id="idCameraLabel1">Frontal</string>
	<string id="idCameraLabel2">2D</string>
	<string id="idModelLabel1">Chico</string>
	<string id="idModelLabel2">Chica</string>
	<string id="idModelLabel3">Niño</string>
	<string id="idModelLabel4">Niña</string>
</metadata>

=== angeldelblanco/eCharacter/assets/Locale/Cubix Studio/Male/en_UK.xml
<?xml version="1.0" encoding="UTF-8"?>
<metadata language="en_UK" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../language.xsd">
	<string id="idPhysicalBuildLabel1">Medium-Built</string>
        <string id="idPhysicalBuildLabel2">Tall</string>
        <string id="idPhysicalBuildLabel3">Small</string>
	<string id="idTextPielCasual">Casual skin</string>
	<string id="idTextPielMedieval">Medieval skin</string>
	<string id="idTextPeloCasual">Casual hair</string>
	<string id="idTextPeloMedieval">Medieval hair</string>
	<string id="idTextOjosCasual">Casual eyes</string>
	<string id="idTextOjosMedieval">Medieval eyes</string>
	<string id="idTextCamisetaCasual">Casual t-shirt</string>
	<string id="idTextCamisetaMedieval">Medieval t-shirt</string>
	<string id="idTextPantalonCasual">Casual trouser</string>
	<string id="idTextPantalonMedieval">Medieval trouser</string>
	<string id="idTextZapatosCasual">Casual shoes</string>
	<string id="idTextZapatosMedieval">Medieval shoes</string>
	<string id="idTextGuantes">Gloves</string>
</metadata>

=== angeldelblanco/eCharacter/assets/Locale/eAdventure/fr_FR.xml
<?xml version="1.0" encoding="UTF-8"?>
<metadata language="fr_FR" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../language.xsd">
	<string id="idNameFamily">eAdventure</string>
	<string id="idDescriptionFamily">Cette famille est composée par 2 humains: un garçon et une fille.</string>
	<string id="idAuthor">Alex,Sergio et David</string>
	<string id="idMultiStageLabel1">Scalaire</string>
	<string id="idBoneControler1">Torse, Tête et bras</string>
	<string id="idBoneControler2">Tête</string>
	<string id="idBoneControler3">Bras</string>
	<string id="idBoneControler4">Gauche</string>
	<string id="idBoneControler5">Main gauche</string>
	<string id="idBoneControler6">Droit</string>
	<string id="idBoneControler7">Main droit</string>
	<string id="idBoneControler8">Jambes</string>
	<string id="idBoneControler9">Gauche</string>
	<string id="idBoneControler10">Pied gauche</string>
	<string id="idBoneControler11">Droit</string>
	<string id="idBoneControler12">Pied droit</string>
	<string id="idMultiStageLabel2">Peau</string>
	<string id="idTextureSubStageLabel1">Skins</string>
	<string id="idMultiStageLabel3">Yeux</string>
	<string id="idTextureSubStageLabel2">Yeux</string>
	<string id="idTextureSubStageLabel3">Surcils et cils</string>
	<string id="idMultiStageLabel4">T-Shirts</string>
	<string id="idTextureSubStageLabel4">T-Shirts</string>
	<string id="idMultiStageLabel5">Pantalons</string>
	<string id="idTextureSubStageLabel5">Pantalons</string>
	<string id="idMultiStageLabel6">Chaussures</string>
	<string id="idTextureSubStageLabel6">Chaussures</string>
	<string id="idTextureSubStageLabel7">Chaussettes</string>
	<string id="idMultiStageLabel7">Cheveaux</string>
	<string id="idTextureSubStageLabel8">Cheveaux</string>
	<string id="idMultiStageLabel8">Accessories</string>
	<string id="idTextureSubStageLabel9">Visage</string>
	<string id="idTextureSubStageLabel10">Accessories du visage</string>
	<string id="idTextureSubStageLabel11">Autres accessories</string>
	<string id="idAnimationStageLabel1">Exportation</string>
	<string id="idQualityLabel1">Haut</string>
	<string id="idQualityLabel2">Moyenne</string>
	<string id="idQualityLabel3">Bas</string>
	<string id="idCameraLabel1">Frontale</string>
	<string id="idCameraLabel2">2D</string>
	<string id="idModelLabel1">Homme</string>
	<string id="idModelLabel2">Femme</string>
	<string id="idModelLabel3">Garçon</string>
	<string id="idModelLabel4">Fille</string>
</metadata>
