=== angeldelblanco/eCharacter/assets/XML Configuration/family.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="family">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="metadata">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="license" type="licenseType" minOccurs="0" maxOccurs="1"/>
							<xs:element name="name" type="xs:string"/>
							<xs:element name="description" type="xs:string"/>
							<xs:element name="author" type="xs:string"/>
							<xs:element name="URL" type="xs:string" minOccurs="0" maxOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="stages">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="scaleStage" type="scaleStageType" minOccurs="1" maxOccurs="10"/>
							<xs:element name="multiStage" type="multiStageType" minOccurs="1" maxOccurs="10"/>	
							<xs:element name="animationStage" type="animationStageType"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="modelsRef">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="modelRef" type="modelRefType" minOccurs="1" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="licenseType">
		<xs:sequence>
			<xs:element name="title" type="xs:string"/>
			<xs:element name="terms" type="xs:string"/>
			<xs:element name="URL" type="xs:string" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="multiStageType">
		<xs:choice minOccurs="1" maxOccurs="unbounded">
			<xs:element name="meshSubStage" type="meshSubStageType"/>
			<xs:element name="textureSubStage" type="textureSubStageType"/>
		</xs:choice>
		<xs:attribute name="stageName" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="meshSubStageType">
		<xs:attribute name="subStageName" type="xs:string" use="required"/>
		<xs:attribute name="idPanel" type="xs:ID" use="required"/>
		<xs:attribute name="multiselection" type="xs:boolean" use="optional"/>
	</xs:complexType>
	<xs:complexType name="textureSubStageType">
		<xs:attribute name="subStageName" type="xs:string" use="required"/>
		<xs:attribute name="idPanel" type="xs:ID" use="required"/>
		<xs:attribute name="multiselection" type="xs:boolean" use="optional"/>
	</xs:complexType>
	<xs:complexType name="scaleStageType">
		<xs:sequence>
			<xs:element name="boneController" minOccurs="1" maxOccurs="10">
				<xs:complexType>
					<xs:attribute name="controllerName" type="xs:string" use="required"/>
					<xs:attribute name="idController" type="xs:ID" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="stageName" type="xs:string" use="required"/>
		<xs:attribute name="idPanel" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:complexType name="animationStageType">
		<xs:sequence>
			<xs:element name="fps" type="fpsType" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element name="camera" type="cameraType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="fpsType">
		<xs:attribute name="qualityName" type="xs:string" use="required"/>
		<xs:attribute name="fpsValue" type="xs:integer" use="required"/>
	</xs:complexType>
	<xs:complexType name="cameraType">
		<xs:sequence>
			<xs:element name="upAxis" type="vectorType"/>
			<xs:element name="location" type="vectorType"/>
			<xs:element name="direction" type="vectorType"/>
		</xs:sequence>
		<xs:attribute name="cameraName" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="vectorType">
		<xs:attribute name="valueX" type="xs:float" use="required"/>
		<xs:attribute name="valueY" type="xs:float" use="required"/>
		<xs:attribute name="valueZ" type="xs:float" use="required"/>
	</xs:complexType>
	<xs:complexType name="modelRefType">
		<xs:sequence>
			<xs:element name="modelName" type="xs:string"/>
			<xs:element name="iconPath" type="xs:string"/>
			<xs:element name="modelPath" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== angeldelblanco/eCharacter/assets/XML Configuration/families/Human 2.xml
<?xml version="1.0" encoding="UTF-8"?>
<family xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../family.xsd">
	<metadata>
		<name>idNameFamily2</name>
		<description>idDescriptionFamily</description>
		<author>idAuthor</author>
		<languagesPath>assets/Locale/Humans 2</languagesPath>
	</metadata>
	<stages>
	<!-- Revisar que controladores poner -->
		<scaleStage stageLabel="idMultiStageLabel1" idPanel="ScalePanel">
			<boneController controllerLabel="idBoneControler1" idController="head"/>
			<boneController controllerLabel="idBoneControler2" idController="torso"/>
			<boneController controllerLabel="idBoneControler3" idController="leftArm"/>
			<boneController controllerLabel="idBoneControler4" idController="rightArm"/>
			<boneController controllerLabel="idBoneControler5" idController="leftHand"/>
			<boneController controllerLabel="idBoneControler6" idController="rightHand"/>
			<boneController controllerLabel="idBoneControler7" idController="leftLeg"/>
			<boneController controllerLabel="idBoneControler8" idController="rightLeg"/>
			<boneController controllerLabel="idBoneControler9" idController="leftFoot"/>
			<boneController controllerLabel="idBoneControler10" idController="rightFoot"/>			
		</scaleStage>
		<multiStage stageLabel="idMultiStageLabel2">
			<subStage subStageType="textureSubStage" subStageLabel="idTextureSubStageLabel1" idPanel="skinsPanel" multiselection="false"/>
		</multiStage>
		<multiStage stageLabel="idMultiStageLabel3">
			<subStage subStageType="textureSubStage" subStageLabel="idTextureSubStageLabel2" idPanel="hairsPanel" multiselection="false"/>
		</multiStage>
		<multiStage stageLabel="idMultiStageLabel4">
			<subStage subStageType="textureSubStage" subStageLabel="idTextureSubStageLabel3" idPanel="eyesPanel" multiselection="false"/>
		</multiStage>
		<multiStage stageLabel="idMultiStageLabel5">
			<subStage subStageType="textureSubStage" subStageLabel="idTextureSubStageLabel4" idPanel="shirtsPanel" multiselection="true"/>
			<subStage subStageType="textureSubStage" subStageLabel="idTextureSubStageLabel5" idPanel="trousersPanel" multiselection="true"/>
		</multiStage>
		<multiStage stageLabel="idMultiStageLabel6">
			<subStage subStageType="textureSubStage" subStageLabel="idTextureSubStageLabel6" idPanel="shoesPanel" multiselection="false"/>
		</multiStage>
		<multiStage stageLabel="idMultiStageLabel7">
			<subStage subStageType="textureSubStage" subStageLabel="idTextureSubStageLabel7" idPanel="accesoriesPanel" multiselection="true"/>
		</multiStage>
		<!-- Revisar la etapa de animaciÃ³n -->
		<animationStage stageLabel="idAnimationStageLabel1">
			<!-- Dar valores. Los que hay son aleatorios -->
			<fps qualityLabel="idQualityLabel1" fpsValue="3"/>
			<fps qualityLabel="idQualityLabel2" fpsValue="2"/>
			<fps qualityLabel="idQualityLabel3" fpsValue="1"/>
			<camera cameraLabel="idCameraLabel1">
				<upAxis valueX="2.0" valueY="2.0" valueZ="2.0"/>
				<location valueX="2.0" valueY="2.0" valueZ="2.0"/>
				<direction valueX="2.0" valueY="2.0" valueZ="2.0"/>
			</camera>
			<camera cameraLabel="idCameraLabel2">
				<upAxis valueX="2.0" valueY="2.0" valueZ="2.0"/>
				<location valueX="2.0" valueY="2.0" valueZ="2.0"/>
				<direction valueX="2.0" valueY="2.0" valueZ="2.0"/>
			</camera>
		</animationStage>
	</stages>
	<modelsRef>
		<modelRef>
			<modelLabel>idModelLabel1</modelLabel>	
			<iconPath>assets/Interface/Icons/Medieval/IconMale.png</iconPath>
			<modelPath>assets/XML Configuration/models/Humans 2/Man.xml</modelPath>
		</modelRef>
		<modelRef>
			<modelLabel>idModelLabel2</modelLabel>
			<iconPath>assets/Interface/Icons/Medieval/IconFemale.png</iconPath>
			<modelPath>assets/XML Configuration/models/Humans 2/Woman.xml</modelPath>
		</modelRef>	
	</modelsRef>
</family>

=== angeldelblanco/eCharacter/assets/Families/Cubix Studio.xml
<?xml version="1.0" encoding="UTF-8"?>
<family xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../family.xsd">
	<metadata>
		<name>idNameFamily</name>
		<abstract>idAbstractFamily</abstract>
		<description>idDescriptionFamily</description>
		<author>idAuthor</author>
		<languagesPath>assets/Families/Cubix Studio/Locale</languagesPath>
		<iconPath>assets/Families/Cubix Studio/Icons/IconoCubix.png</iconPath>
	</metadata>
	<stages>
		<scaleStage stageLabel="idMultiStageLabel1" idPanel="ScalePanel">
			<iconPath>assets/Families/Cubix Studio/Icons/IconosBarraSuperior_0000_Complexion.png</iconPath>
			<boneController controllerLabel="idBoneControler1" idController="head" level="0"/>
			<boneController controllerLabel="idBoneControler2" idController="arms" level="0"/>
			<boneController controllerLabel="idBoneControler3" idController="hands" level="0"/>
			<boneController controllerLabel="idBoneControler4" idController="legs" level="0"/>
			<boneController controllerLabel="idBoneControler5" idController="feet" level="0"/>
		</scaleStage>
		<multiStage stageLabel="idMultiStageLabel2">
			<iconPath>assets/Families/Cubix Studio/Icons/IconosBarraSuperior_0001_Piel.png</iconPath>
			<subStage subStageType="textureSubStage" subStageLabel="idTextureSubStageLabel1" idPanel="skinsPanel" multiselection="false"/>
		</multiStage>
		<multiStage stageLabel="idMultiStageLabel3">
			<iconPath>assets/Families/Cubix Studio/Icons/IconosBarraSuperior_0006_Pelo.png</iconPath>
			<subStage subStageType="textureSubStage" subStageLabel="idTextureSubStageLabel2" idPanel="hairsPanel" multiselection="false"/>
		</multiStage>
		<multiStage stageLabel="idMultiStageLabel4">
			<iconPath>assets/Families/Cubix Studio/Icons/IconosBarraSuperior_0002_Ojos.png</iconPath>
			<subStage subStageType="textureSubStage" subStageLabel="idTextureSubStageLabel3" idPanel="eyesPanel" multiselection="false"/>
		</multiStage>
		<multiStage stageLabel="idMultiStageLabel5">
			<iconPath>assets/Families/Cubix Studio/Icons/IconosBarraSuperior_0003_Camiseta.png</iconPath>
			<subStage subStageType="textureSubStage" subStageLabel="idTextureSubStageLabel4" idPanel="shirtsPanel" multiselection="false"/>
			<subStage subStageType="textureSubStage" subStageLabel="idTextureSubStageLabel5" idPanel="trousersPanel" multiselection="false"/>
                        <!--<subStage subStageType="textureSubStage" subStageLabel="idTextureSubStageLabel5b" idPanel="baseColorPanel" multiselection="false"/>-->
		</multiStage>
		<multiStage stageLabel="idMultiStageLabel6">
			<iconPath>assets/Families/Cubix Studio/Icons/IconosBarraSuperior_0005_Calzado.png</iconPath>
			<subStage subStageType="textureSubStage" subStageLabel="idTextureSubStageLabel6" idPanel="shoesPanel" multiselection="false"/>
		</multiStage>
		<multiStage stageLabel="idMultiStageLabel7">
			<iconPath>assets/Families/Cubix Studio/Icons/IconosBarraSuperior_0007_Accesorios.png</iconPath>
			<subStage subStageType="textureSubStage" subStageLabel="idTextureSubStageLabel7" idPanel="accesoriesPanel" multiselection="true"/>
		</multiStage>
		<animationStage stageLabel="idAnimationStageLabel1">
			<fps qualityLabel="idQualityLabel1" fpsValue="24"/>
			<fps qualityLabel="idQualityLabel2" fpsValue="12"/>
			<fps qualityLabel="idQualityLabel3" fpsValue="6"/>
			<camera cameraLabel="idCameraLabel1">
				<upAxis valueX="0.0" valueY="1.0" valueZ="0.0"/>
				<location valueX="0.0" valueY="0.0" valueZ="11.0"/>
				<direction valueX="0.0" valueY="0.0" valueZ="-1.0"/>
			</camera>
			<camera cameraLabel="idCameraLabel2">
				<upAxis valueX="0.0" valueY="1.0" valueZ="0.0"/>
				<location valueX="-2.25" valueY="2.0" valueZ="11.0"/>
				<direction valueX="0.0" valueY="0.0" valueZ="-1.0"/>
			</camera>
		</animationStage>
	</stages>
	<modelsRef>
		<modelRef>
			<modelLabel>idModelLabel1</modelLabel>	
			<iconPath>assets/Families/Cubix Studio/Icons/Cubix-Hombre.png</iconPath>
			<modelPath>assets/Families/Cubix Studio/XML models/Male.xml</modelPath>
		</modelRef>
		<modelRef>
			<modelLabel>idModelLabel2</modelLabel>
			<iconPath>assets/Families/Cubix Studio/Icons/Cubix-Mujer.png</iconPath>
			<modelPath>assets/Families/Cubix Studio/XML models/Female.xml</modelPath>
		</modelRef>	
	</modelsRef>
</family>

=== angeldelblanco/eCharacter/assets/Families/Characters.xml
<?xml version="1.0" encoding="UTF-8"?>
<family xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\Sergio\jMonkeyEngine\eCharacter\assets\XSD\family.xsd">
	<metadata>
		<name>idNameFamily</name>
		<abstract>idAbstractFamily</abstract>
		<description>idDescriptionFamily</description>
		<author>idAuthor</author>
		<languagesPath>assets/Families/Characters/Locale</languagesPath>
		<iconPath>assets/Families/Characters/Icons/IconoCharacters.png</iconPath>
	</metadata>
	<stages>
		<scaleStage stageLabel="idMultiStageLabel1" idPanel="ScalePanel">
			<iconPath>assets/Families/Characters/Icons/IconosBarraSuperior_0000_Complexion.png</iconPath>
			<boneController controllerLabel="idBoneControler1" idController="torsoHeadArms" level="0"/>
		</scaleStage>
		<multiStage stageLabel="idMultiStageLabel2">
			<iconPath>assets/Families/Characters/Icons/IconosBarraSuperior_0001_Piel.png</iconPath>
			<subStage subStageType="textureSubStage" subStageLabel="idTextureSubStageLabel1" idPanel="clothesPanel" multiselection="false"/>
		</multiStage>
		<animationStage stageLabel="idAnimationStageLabel1">
			<!-- Dar valores. Los que hay son aleatorios -->
			<fps qualityLabel="idQualityLabel1" fpsValue="24"/>
			<fps qualityLabel="idQualityLabel2" fpsValue="12"/>
			<fps qualityLabel="idQualityLabel3" fpsValue="6"/>
			<camera cameraLabel="idCameraLabel1">
				<upAxis valueX="0.0" valueY="1.0" valueZ="0.0"/>
				<location valueX="0.0" valueY="0.0" valueZ="11.0"/>
				<direction valueX="0.0" valueY="0.0" valueZ="-1.0"/>
			</camera>
			<camera cameraLabel="idCameraLabel2">
				<upAxis valueX="0.0" valueY="1.0" valueZ="0.0"/>
				<location valueX="-2.5" valueY="3.0" valueZ="11.0"/>
				<direction valueX="0.0" valueY="0.0" valueZ="-1.0"/>
			</camera>
		</animationStage>
	</stages>
	<modelsRef>
		<modelRef>
			<modelLabel>idModelLabel1</modelLabel>
			<iconPath>assets/Families/Characters/Icons/ninja.png</iconPath>
			<modelPath>assets/Families/Characters/XML models/ninja.xml</modelPath>
		</modelRef>	
		<modelRef>
			<modelLabel>idModelLabel2</modelLabel>
			<iconPath>assets/Families/Characters/Icons/zombie.png</iconPath>
			<modelPath>assets/Families/Characters/XML models/zombie.xml</modelPath>
		</modelRef>
	</modelsRef>
</family>

=== angeldelblanco/eCharacter/assets/XML Configuration/families/Dogs.xml
<?xml version="1.0" encoding="UTF-8"?>
<family xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../family.xsd">
	<metadata>
		<name>Dogs</name>
		<description>Esta familia está compuesta por 2 perros: un yorkshire y un samoyedo.</description>
		<author>Sergio.</author>
	</metadata>
	<stages>
		<scaleStage stageName="Escalado" idPanel="panelEscalado">
			<boneController controllerName="Cabeza" idController="cabeza"/>
			<boneController controllerName="Torax" idController="torax"/>
			<boneController controllerName="Muñeca Izquierda" idController="muniecaIzq"/>
			<boneController controllerName="Muñeca Derecha" idController="muniecaDer"/>
			<boneController controllerName="Tobillo Izquierdo" idController="tobilloIzq"/>
			<boneController controllerName="Tobillo Derecho" idController="tobilloDer"/>
			<boneController controllerName="Fémur Izquierdo" idController="femurIzq"/>
			<boneController controllerName="Fémur Derecho" idController="femurDer"/>
			<boneController controllerName="Clavícula Izquierda" idController="claviculaIzq"/>
			<boneController controllerName="Clavícula Derecha" idController="claviculaDer"/>
		</scaleStage>
		<multiStage stageName="Piel">
			<textureSubStage subStageName="Pieles" idPanel="panelPieles" multiselection="false"/>
		</multiStage>
		<multiStage stageName="Ojos">
			<textureSubStage subStageName="Ojos" idPanel="panelOjos" multiselection="false"/>
		</multiStage>
		<multiStage stageName="Camiseta">
			<textureSubStage subStageName="Camisetas" idPanel="panelCamisetas" multiselection="false"/>
		</multiStage>
		<multiStage stageName="Pantalón">
			<textureSubStage subStageName="Pantalones" idPanel="panelPantalones" multiselection="false"/>
		</multiStage>
		
		<multiStage stageName="Zapatos">
			<textureSubStage subStageName="Zapatos" idPanel="panelZapatos" multiselection="false"/>
		</multiStage>

		<multiStage stageName="Pelo">
			<meshSubStage subStageName="Pelos" idPanel="panelPelos" multiselection="false"/>
		</multiStage>
		<animationStage>
			<!-- Dar valores. Los que hay son aleatorios -->
			<fps qualityName="High" fpsValue="2"/>
			<camera cameraName="Delante">
				<upAxis valueX="2.0" valueY="2.0" valueZ="2.0"/>
				<location valueX="2.0" valueY="2.0" valueZ="2.0"/>
				<direction valueX="2.0" valueY="2.0" valueZ="2.0"/>
			</camera>
		</animationStage>
	</stages>
	<modelsRef>
		<modelRef>
			<modelName>Yorkshire</modelName>
			<iconPath>Interface/yorkshire.png</iconPath>
			<modelPath></modelPath>
		</modelRef> 
		<modelRef>
			<modelName>Samoyedo</modelName>
			<iconPath>Interface/samoyedo.png</iconPath>
			<modelPath></modelPath>
		</modelRef> 
	</modelsRef>
</family>

=== angeldelblanco/eCharacter/assets/Families/Animals.xml
<?xml version="1.0" encoding="UTF-8"?>
<family xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\Sergio\jMonkeyEngine\eCharacter\assets\XSD\family.xsd">
	<metadata>
		<name>idNameFamily</name>
		<abstract>idAbstractFamily</abstract>
		<description>idDescriptionFamily</description>
		<author>idAuthor</author>
		<languagesPath>assets/Families/Animals/Locale</languagesPath>
		<iconPath>assets/Families/Animals/Icons/IconoAnimals.png</iconPath>
	</metadata>
	<stages>
		<scaleStage stageLabel="idMultiStageLabel1" idPanel="ScalePanel">
			<iconPath>assets/Families/Animals/Icons/IconosBarraSuperior_0000_Complexion.png</iconPath>
			<boneController controllerLabel="idBoneControler1" idController="torsoHeadArms" level="0"/>
		</scaleStage>
		<multiStage stageLabel="idMultiStageLabel2">
			<iconPath>assets/Families/Animals/Icons/IconosBarraSuperior_0001_Piel.png</iconPath>
			<subStage subStageType="textureSubStage" subStageLabel="idTextureSubStageLabel1" idPanel="skinsPanel" multiselection="false"/>
		</multiStage>
		<animationStage stageLabel="idAnimationStageLabel1">
			<!-- Dar valores. Los que hay son aleatorios -->
			<fps qualityLabel="idQualityLabel1" fpsValue="24"/>
			<fps qualityLabel="idQualityLabel2" fpsValue="12"/>
			<fps qualityLabel="idQualityLabel3" fpsValue="6"/>
			<camera cameraLabel="idCameraLabel1">
				<upAxis valueX="0.0" valueY="1.0" valueZ="0.0"/>
				<location valueX="0.0" valueY="0.0" valueZ="11.0"/>
				<direction valueX="0.0" valueY="0.0" valueZ="-1.0"/>
			</camera>
			<camera cameraLabel="idCameraLabel2">
				<upAxis valueX="0.0" valueY="1.0" valueZ="0.0"/>
				<location valueX="-2.5" valueY="3.0" valueZ="11.0"/>
				<direction valueX="0.0" valueY="0.0" valueZ="-1.0"/>
			</camera>
		</animationStage>
	</stages>
	<modelsRef>
		<modelRef>
			<modelLabel>idModelLabel1</modelLabel>
			<iconPath>assets/Families/Animals/Icons/dog.png</iconPath>
			<modelPath>assets/Families/Animals/XML models/dog.xml</modelPath>
		</modelRef>	
		<modelRef>
			<modelLabel>idModelLabel2</modelLabel>
			<iconPath>assets/Families/Animals/Icons/cat.png</iconPath>
			<modelPath>assets/Families/Animals/XML models/cat.xml</modelPath>
		</modelRef>
	</modelsRef>
</family>
