=== angeldelblanco/eCharacter/assets/XML Configuration/model.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="model">
		<xs:complexType>
			<xs:sequence>
				<!-- This node defines all the textures, physical builds, initial transformations and all the bones to scale. -->
				<xs:element name="mainMesh" type="mainMeshType"/>
				<!-- This node defines all the submeshes of the model -->
				<xs:element name="subMesh" type="subMeshType" minOccurs="0" maxOccurs="unbounded"/>
				<!-- This node define the languages path of the model -->
				<xs:element name="languagesPath" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="meshType">
		<xs:sequence>
			<!-- This node define the mesh path -->
			<xs:element name="path" type="xs:string"/>
			<!-- This node define the list of initial transformations to make to the model -->
			<xs:element name="transformation" type="transformationType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="mainMeshType">
		<xs:complexContent>
			<xs:extension base="meshType">
				<xs:sequence>
					<!-- This node define the list of the textures of the model -->
					<xs:element name="mainMeshTextures" minOccurs="0" maxOccurs="1">
						<xs:complexType>
							<xs:choice minOccurs="1" maxOccurs="unbounded">
								<xs:element name="baseShadowTexture" type="baseShadowTextureType"/>
								<xs:element name="simpleTexture" type="simpleTextureType"/>
								<xs:element name="doubleTexture" type="doubleTextureType"/>
								<xs:element name="multiOptionTexture" type="multiOptionTextureType"/>
							</xs:choice>
						</xs:complexType>
					</xs:element>
					<!-- This node define the list of the bones to scale -->
					<xs:element name="bones" type="bonesType"/>
					<!-- This node define the list of the physical builds of the model -->
					<xs:element name="physicalBuilds" type="physicalBuildsType"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="subMeshType">
		<xs:complexContent>
			<xs:extension base="meshType">
				<xs:sequence>
					<!-- This node is similar to mainMeshType but in this case only can have one texture associated.-->
					<xs:element name="subMeshTexture" minOccurs="0" maxOccurs="1">
						<xs:complexType>
							<xs:choice>
								<xs:element name="baseShadowTextureSubMesh" type="baseShadowTextureSubMeshType"/>
								<xs:element name="simpleTextureSubMesh" type="simpleTextureSubMeshType"/>
								<xs:element name="doubleTextureSubMesh" type="doubleTextureSubMeshType"/>
								<xs:element name="multiOptionTextureSubMesh" type="multiOptionTextureSubMeshType"/>
							</xs:choice>
						</xs:complexType>
					</xs:element>
					<xs:element name="iconPath" type="xs:string"/>
				</xs:sequence>
				<!-- This attribute indicates the panel where it has to load this texture -->
				<xs:attribute name="idPanelRef" type="xs:string" use="required"/>
				<!--This attribute indicates the bone which the submesh is associated.-->
				<xs:attribute name="associatedBone" type="xs:string" use="required"/>
				<!-- This attribute indicates the id of this submesh Must be unique! -->
				<xs:attribute name="idSubMesh" type="xs:ID" use="required"/>
				<!-- If default is true, this submesh will appear when the model is loaded initially.-->
				<xs:attribute name="default" type="xs:boolean" use="required"/>
				<xs:attribute name="text" type="xs:string" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<!-- This node is the generic type of a texture. All the textures have these fields. -->
	<xs:complexType name="textureType">
		<xs:sequence>
			<xs:element name="iconPath" type="xs:string"/>
		</xs:sequence>
		<!-- This attribute indicates the panel where it has to load this texture -->
		<xs:attribute name="idPanelRef" type="xs:string" use="required"/>
		<!-- This attribute indicates the priority of this texture. Lower value indicates higher priority.(Highest priority is layer=0) -->
		<xs:attribute name="layer" type="xs:integer" use="required"/>
		<!-- This attribute indicates the id of this texture. Must be unique! -->
		<xs:attribute name="idTexture" type="xs:ID" use="required"/>
		<xs:attribute name="text" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="baseShadowTextureType">
		<xs:complexContent>
			<xs:extension base="textureType">
				<xs:sequence>
					<!-- base path.-->
					<xs:element name="path" type="xs:string"/>
					<!-- RGB value which is initially loaded in the texture.-->
					<xs:element name="colorDefault" type="colorType"/>
					<xs:element name="shadowPath" type="xs:string" minOccurs="0" maxOccurs="1"/>
				</xs:sequence>
				<!-- If default is true, this texture will appear when the model is loaded initially.-->
				<xs:attribute name="default" type="xs:boolean" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="colorType">
		<xs:sequence>
			<xs:element name="red" type="xs:integer"/>
			<xs:element name="green" type="xs:integer"/>
			<xs:element name="blue" type="xs:integer"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="simpleTextureType">
		<xs:complexContent>
			<xs:extension base="textureType">
				<xs:sequence>
					<xs:element name="path" type="xs:string"/>
				</xs:sequence>
				<xs:attribute name="default" type="xs:boolean" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="doubleTextureType">
		<xs:complexContent>
			<xs:extension base="textureType">
				<xs:sequence>
					<xs:element name="basePath" type="xs:string"/>
					<xs:element name="detailsPath" type="xs:string"/>
				</xs:sequence>
				<xs:attribute name="default" type="xs:boolean" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="multiOptionTextureType">
		<xs:complexContent>
			<xs:extension base="textureType">
				<xs:sequence>
					<xs:element name="optionTexture" minOccurs="1" maxOccurs="unbounded">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="path" type="xs:string"/>
								<xs:element name="iconPath" type="xs:string"/>
							</xs:sequence>
							<!-- This attribute indicates the id of this subtexture. Must be unique! -->
							<xs:attribute name="idSubTexture" type="xs:ID" use="required"/>
							<!-- If default is true, this subtexture will appear when the model is loaded initially.-->
							<xs:attribute name="default" type="xs:boolean" use="required"/>
							<xs:attribute name="text" type="xs:string" use="required"/>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<!-- Textures SubMeshes -->
	<xs:complexType name="textureSubMeshType">
		<!-- This attribute indicates the priority of this texture.
			 Lower value indicates higher priority.(Highest priority is layer=0) -->
		<xs:attribute name="layer" type="xs:integer" use="required"/>
		<xs:attribute name="idTexture" type="xs:ID" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="baseShadowTextureSubMeshType">
		<xs:complexContent>
			<xs:extension base="textureSubMeshType">
				<xs:sequence>
					<!--Base path.-->
					<xs:element name="path" type="xs:string"/>
					<xs:element name="shadowPath" type="xs:string" minOccurs="0" maxOccurs="1"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="simpleTextureSubMeshType">
		<xs:complexContent>
			<xs:extension base="textureSubMeshType">
				<xs:sequence>
					<xs:element name="path" type="xs:string"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="doubleTextureSubMeshType">
		<xs:complexContent>
			<xs:extension base="textureSubMeshType">
				<xs:sequence>
					<xs:element name="basePath" type="xs:string"/>
					<xs:element name="detailsPath" type="xs:string"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="multiOptionTextureSubMeshType">
		<xs:complexContent>
			<xs:extension base="textureSubMeshType">
				<xs:sequence>
					<xs:element name="optionTexture" minOccurs="1" maxOccurs="unbounded">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="path" type="xs:string"/>
								<xs:element name="iconPath" type="xs:string"/>
							</xs:sequence>
							<!-- This attribute indicates the id of this subtexture. Must be unique! -->
							<xs:attribute name="idSubTexture" type="xs:ID" use="required"/>
							<!-- If default is true, this subtexture will appear when the model is loaded initially.-->
							<xs:attribute name="default" type="xs:boolean" use="required"/>
							<xs:attribute name="text" type="xs:string" use="required"/>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="bonesType">
		<xs:sequence>
			<xs:element name="bone" type="boneType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="boneType">
		<!--This attribute indicates the controller defined in XML family with which it is associated.-->
		<xs:attribute name="idControllerRef" type="xs:string" use="required"/>
		<xs:attribute name="defaultValue" type="xs:float" use="required"/>
		<xs:attribute name="minValue" type="xs:float" use="required"/>
		<xs:attribute name="maxValue" type="xs:float" use="required"/>
		<xs:attribute name="boneName" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="physicalBuildsType">
		<xs:sequence>
			<xs:element name="physicalBuild" type="physicalBuildType" minOccurs="1" maxOccurs="10"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="physicalBuildType">
		<!--This attributes indicates the escalations sequence that will be applied to model.-->
		<xs:sequence>
			<xs:element name="escalation" type="escalationType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
		<!-- This attribute indicates the panel where it has to load this texture -->
		<xs:attribute name="idPanelRef" type="xs:string" use="required"/>
		<xs:attribute name="label" type="xs:string" use="required"/>
		<!-- This attribute indicates the id of this physical build. Must be unique! -->
		<xs:attribute name="idPhysicalBuild" type="xs:ID" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="escalationType">
		<xs:attribute name="boneName" type="xs:string" use="required"/>
		<!-- These fields define the values of the transformations on each axis. -->
		<xs:attribute name="valueX" type="xs:float" use="required"/>
		<xs:attribute name="valueY" type="xs:float" use="required"/>
		<xs:attribute name="valueZ" type="xs:float" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="transformationType">
		<xs:attribute name="transformationType" use="required">
			<!-- This field defines the type of the transformation (scale, rotate or translate). -->
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="scale"/>
					<xs:enumeration value="rotate"/>
					<xs:enumeration value="translate"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<!-- These fields define the values of the transformations on each axis. -->
		<xs:attribute name="valueX" type="xs:float" use="required"/>
		<xs:attribute name="valueY" type="xs:float" use="required"/>
		<xs:attribute name="valueZ" type="xs:float" use="required"/>		
	</xs:complexType>
	
</xs:schema>

=== angeldelblanco/eCharacter/assets/XML Configuration/models/Medieval/Male.xml
<?xml version="1.0" encoding="UTF-8"?>
<model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../model.xsd">
	<mainMesh>
		<path>assets\Models\Medieval\Male\CubixStudioMaleNPC.mesh.xml</path>		
		<!--Transformations-->
		<transformation transformationType="rotate" valueX="0.0" valueY="-90.0" valueZ="0.0"></transformation>
                <transformation transformationType="scale" valueX="2.25" valueY="2.25" valueZ="2.25"></transformation>
                <transformation transformationType="translate" valueX="-0.25" valueY="-2.5" valueZ="0.0"></transformation>
                <!--Textures-->
		<mainMeshTextures>
			<!-- skinPanel textures-->
			<simpleTexture idPanelRef="skinsPanel" layer="0" default="true" idTexture="idPielCasual"  text="idTextPielCasual">
				<iconPath>assets\Interface\Icons\eAdventure\Boy\IconoPielBlancaBoy.png</iconPath>
				<path>assets\Textures\Medieval\Male\SkinMaleCasual.png</path>
			</simpleTexture>
			<simpleTexture idPanelRef="skinsPanel" layer="0" default="false" idTexture="idPielMedieval"  text="idTextPielMedieval">
				<iconPath>assets\Interface\Icons\eAdventure\Boy\IconoPielNegraBoy.png</iconPath>
				<path>assets\Textures\Medieval\Male\SkinMaleMedieval.png</path>
			</simpleTexture>
			<!-- hairs textures -->
			<simpleTexture idPanelRef="hairsPanel" layer="0" idTexture="idPeloCasual" default="true"  text="idTextPeloCasual">
				<iconPath>assets\Interface\Icons\eAdventure\Boy\IconoPielNegraBoy.png</iconPath>
				<path>assets\Textures\Medieval\Male\HairMaleCasual.png</path>
			</simpleTexture>
			<simpleTexture idPanelRef="hairsPanel" layer="0" idTexture="idPeloMedieval" default="false"  text="idTextPeloMedieval">
				<iconPath>assets\Interface\Icons\eAdventure\Boy\IconoPielBlancaBoy.png</iconPath>
				<path>assets\Textures\Medieval\Male\HairMaleMedieval.png</path>
			</simpleTexture>
			<!-- eyes textures-->
			<simpleTexture idPanelRef="eyesPanel" layer="1" idTexture="idOjosCasual" default="true"  text="idTextOjosCasual">
				<iconPath>assets\Interface\Icons\eAdventure\Boy\IconoOjosBoy.png</iconPath>
				<path>assets\Textures\Medieval\Male\EyesMaleCasual.png</path>
			</simpleTexture>
			<simpleTexture idPanelRef="eyesPanel" layer="1" idTexture="idOjosMedieval" default="false"  text="idTextOjosMedieval">
				<iconPath>assets\Interface\Icons\eAdventure\Boy\IconoOjosBoy.png</iconPath>
				<path>assets\Textures\Medieval\Male\EyesMaleMedieval.png</path>
			</simpleTexture>
			<!-- tshirtsPanel textures-->	
			<simpleTexture idPanelRef="shirtsPanel" layer="0" idTexture="idCamisetaCasual" default="true"	 text="idTextCamisetaCasual">
				<iconPath>assets\Interface\Icons\eAdventure\Boy\IconoCamisaCortaBoy.png</iconPath>
				<path>assets\Textures\Medieval\Male\ShirtSolidMaleCasual.png</path>
			</simpleTexture>
			<simpleTexture idPanelRef="shirtsPanel" layer="0" idTexture="idCamisetaMedieval" default="false"	 text="idTextCamisetaMedieval">
				<iconPath>assets\Interface\Icons\eAdventure\Boy\IconoCamisaLargaBoy.png</iconPath>
				<path>assets\Textures\Medieval\Male\ClothSolidMaleMedieval.png</path>
			</simpleTexture>
			<!-- trousersPanel textures-->
			<simpleTexture idPanelRef="trousersPanel" layer="0" idTexture="idPantalonCasual" default="true" text="idTextPantalonCasual">
				<iconPath>assets\Interface\Icons\eAdventure\Boy\IconoPantalonCortoBoy.png</iconPath>
				<path>assets\Textures\Medieval\Male\TrousersSolidMaleCasual.png</path>
			</simpleTexture>
			<simpleTexture idPanelRef="trousersPanel" layer="0" idTexture="idPantalonMedieval" default="false" text="idTextPantalonMedieval">
				<iconPath>assets\Interface\Icons\eAdventure\Boy\IconoPantalonLargoBoy.png</iconPath>
				<path>assets\Textures\Medieval\Male\TrousersMaleMedieval.png</path>
			</simpleTexture>		
			<!-- shoesPanel textures-->
			<simpleTexture idPanelRef="shoesPanel" layer="0" idTexture="idZapatosCasual" default="true" text="idTextZapatosCasual">
				<iconPath>assets\Interface\Icons\eAdventure\Boy\IconoZapatosBoy.png</iconPath>
				<path>assets\Textures\Medieval\Male\ShoesSolidMaleCasual.png</path>
			</simpleTexture>
			<simpleTexture idPanelRef="shoesPanel" layer="0" idTexture="idZapatosMedieval" default="false" text="idTextZapatosMedieval">
				<iconPath>assets\Interface\Icons\eAdventure\Boy\IconoZapatosBoy.png</iconPath>
				<path>assets\Textures\Medieval\Male\ShoesMaleMedieval.png</path>
			</simpleTexture>
			<!-- accesoriesPanel textures-->
			<simpleTexture idPanelRef="accesoriesPanel" layer="1" idTexture="idGuantes" default="false" text="idTextGuantes">
				<iconPath>assets\Textures\Medieval\Male\GlovesMaleMedieval.png</iconPath>
				<path>assets\Textures\Medieval\Male\GlovesMaleMedieval.png</path>
			</simpleTexture>
		</mainMeshTextures>		
		<!--Bones-->
		<bones>
			<!-- Dar valores a los huesos, Los que hay son aleatorios -->
			<bone idControllerRef="head" defaultValue="0" minValue="-50" maxValue="50" boneName="Bip01_Head"/>
			<bone idControllerRef="arms" defaultValue="0" minValue="-50" maxValue="50" boneName="Bip01_L_Clavicle"/>
			<bone idControllerRef="arms" defaultValue="0" minValue="-50" maxValue="50" boneName="Bip01_R_Clavicle"/>
			<bone idControllerRef="hands" defaultValue="0" minValue="-50" maxValue="50" boneName="Bip01_L_Hand"/>
			<bone idControllerRef="hands" defaultValue="0" minValue="-50" maxValue="50" boneName="Bip01_R_Hand"/>
			<bone idControllerRef="legs" defaultValue="0" minValue="-50" maxValue="50" boneName="Bip01_L_Thigh"/>
			<bone idControllerRef="legs" defaultValue="0" minValue="-50" maxValue="50" boneName="Bip01_R_Thigh"/>
			<bone idControllerRef="feet" defaultValue="0" minValue="-50" maxValue="50" boneName="Bip01_L_Foot"/>
			<bone idControllerRef="feet" defaultValue="0" minValue="-50" maxValue="50" boneName="Bip01_R_Foot"/>
		</bones>		
		<!--Physical Builds-->
		<physicalBuilds>
			<physicalBuild label="idPhysicalBuildLabel1" idPanelRef="ScalePanel" idPhysicalBuild="idMediumBuilt">
				<escalation boneName="ALL" valueX="1.0" valueY="1.0" valueZ="1.0"/>
                                <escalation boneName="Cabeza" valueX="1.0" valueY="1.0" valueZ="1.0"/>
			</physicalBuild>
			<physicalBuild label="idPhysicalBuildLabel2" idPanelRef="ScalePanel" idPhysicalBuild="idHeavy">
				<escalation boneName="ALL" valueX="1.50" valueY="1.0" valueZ="1.0"/>
				<escalation boneName="Cabeza" valueX="0.66" valueY="1.0" valueZ="1.0"/>
			</physicalBuild>
			<physicalBuild label="idPhysicalBuildLabel3" idPanelRef="ScalePanel" idPhysicalBuild="idThin">
				<escalation boneName="ALL" valueX="0.65" valueY="1.0" valueZ="1.0"/>
				<escalation boneName="Cabeza" valueX="1.54" valueY="1.0" valueZ="1.0"/>
			</physicalBuild>
			<physicalBuild label="idPhysicalBuildLabel4" idPanelRef="ScalePanel" idPhysicalBuild="idTall">
				<escalation boneName="ALL" valueX="1.1" valueY="1.25" valueZ="1.25"/>
				<escalation boneName="Cabeza" valueX="0.91" valueY="0.8" valueZ="0.8"/>
			</physicalBuild>
			<physicalBuild label="idPhysicalBuildLabel5" idPanelRef="ScalePanel" idPhysicalBuild="idSmall">
				<escalation boneName="ALL" valueX="0.9" valueY="0.75" valueZ="0.75"/>
				<escalation boneName="Cabeza" valueX="1.11" valueY="1.33" valueZ="1.33"/>
			</physicalBuild>
		</physicalBuilds>
	</mainMesh>	
	<languagesPath>assets\Locale\Medieval\Male</languagesPath>
</model>

=== angeldelblanco/eCharacter/assets/Families/Cubix Studio/XML models/Female.xml
<?xml version="1.0" encoding="UTF-8"?>
<model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../model.xsd">
	<mainMesh>
		<path>assets/Families/Cubix Studio/Models/Female/CubixStudioFemaleNPC.mesh.xml</path>		
		<!--Transformations-->
		<transformation transformationType="rotate" valueX="0.0" valueY="-77.0" valueZ="0.0"></transformation>
                <transformation transformationType="scale" valueX="2.25" valueY="2.25" valueZ="2.25"></transformation>
                <transformation transformationType="translate" valueX="-2.65" valueY="-2.9" valueZ="0.0"></transformation>
                <!--Textures-->
		<mainMeshTextures>
			<!-- skinPanel textures-->
			<simpleTexture idPanelRef="skinsPanel" layer="0" default="true" idTexture="idPielCasual" text="idTextPielCasual">
				<iconPath>assets/Families/eAdventure/Icons/Boy/IconoPielBlancaBoy.png</iconPath>
				<path>assets/Families/Cubix Studio/Textures/Female/SkinFemaleCasual.png</path>
			</simpleTexture>
			<simpleTexture idPanelRef="skinsPanel" layer="0" default="false" idTexture="idPielMedieval" text="idTextPielMedieval">
				<iconPath>assets/Families/eAdventure/Icons/Boy/IconoPielNegraBoy.png</iconPath>
				<path>assets/Families/Cubix Studio/Textures/Female/SkinFemaleMedieval.png</path>
			</simpleTexture>
			<!-- hairs textures -->
			<simpleTexture idPanelRef="hairsPanel" layer="0" idTexture="idPeloCasual" default="true"  text="idTextPeloCasual">
				<iconPath>assets/Families/eAdventure/Icons/Boy/IconoPielNegraBoy.png</iconPath>
				<path>assets/Families/Cubix Studio/Textures/Female/HairFemaleCasual.png</path>
			</simpleTexture>
			<simpleTexture idPanelRef="hairsPanel" layer="0" idTexture="idPeloMedieval" default="false"  text="idTextPeloMedieval">
				<iconPath>assets/Families/eAdventure/Icons/Boy/IconoPielBlancaBoy.png</iconPath>
				<path>assets/Families/Cubix Studio/Textures/Female/HairFemaleMedieval.png</path>
			</simpleTexture>
			<!-- eyes textures-->
			<simpleTexture idPanelRef="eyesPanel" layer="1" idTexture="idOjosCasual" default="true"  text="idTextOjosCasual">
				<iconPath>assets/Families/eAdventure/Icons/Boy/IconoOjosBoy.png</iconPath>
				<path>assets/Families/Cubix Studio/Textures/Female/EyeColorFemaleCasual.png</path>
			</simpleTexture>
			<simpleTexture idPanelRef="eyesPanel" layer="1" idTexture="idOjosMedieval" default="false"  text="idTextOjosMedieval">
				<iconPath>assets/Families/eAdventure/Icons/Boy/IconoOjosBoy.png</iconPath>
				<path>assets/Families/Cubix Studio/Textures/Female/EyeColorFemaleMedieval.png</path>
			</simpleTexture>
			<!-- clothesPanel textures-->	
			<simpleTexture idPanelRef="shirtsPanel" layer="0" idTexture="idCamisetaCasual" default="true"	  text="idTextCamisetaCasual">
				<iconPath>assets/Families/eAdventure/Icons/Boy/IconoCamisaCortaBoy.png</iconPath>
				<path>assets/Families/Cubix Studio/Textures/Female/CoatFemaleCasual.png</path>
			</simpleTexture>
			<simpleTexture idPanelRef="trousersPanel" layer="0" idTexture="idFaldaCasual" default="true" text="idTextFaldaCasual">
				<iconPath>assets/Families/eAdventure/Icons/Boy/IconoPantalonCortoBoy.png</iconPath>
				<path>assets/Families/Cubix Studio/Textures/Female/SkirtFemaleCasual.png</path>
			</simpleTexture>
			<simpleTexture idPanelRef="shirtsPanel" layer="0" idTexture="idVestidoMedieval" default="false"  text="idTextVestidoMedieval">
				<iconPath>assets/Families/eAdventure/Icons/Boy/IconoCamisaLargaBoy.png</iconPath>
				<path>assets/Families/Cubix Studio/Textures/Female/ClothFemaleMedieval.png</path>
			</simpleTexture>
			<!-- shoesPanel textures-->
			<simpleTexture idPanelRef="shoesPanel" layer="0" idTexture="idZapatosCasual" default="true"  text="idTextZapatosCasual">
				<iconPath>assets/Families/eAdventure/Icons/Boy/IconoZapatosBoy.png</iconPath>
				<path>assets/Families/Cubix Studio/Textures/Female/ShoesFemaleCasual.png</path>
			</simpleTexture>
			<simpleTexture idPanelRef="shoesPanel" layer="1" idTexture="idZapatosMedieval" default="false"  text="idTextZapatosMedieval">
				<iconPath>assets/Families/eAdventure/Icons/Boy/IconoZapatosBoy.png</iconPath>
				<path>assets/Families/Cubix Studio/Textures/Female/BootsFemaleMedieval.png</path>
			</simpleTexture>
			<!-- accesoriesPanel textures-->
			<simpleTexture idPanelRef="accesoriesPanel" layer="1" idTexture="idRopaInterior" default="true"  text="idTextRopaInterior">
				<iconPath>assets/Families/Cubix Studio/Textures/Female/UnderwearFemaleCasual.png</iconPath>
				<path>assets/Families/Cubix Studio/Textures/Female/UnderwearFemaleCasual.png</path>
			</simpleTexture>
			<simpleTexture idPanelRef="accesoriesPanel" layer="1" idTexture="idCinta" default="false"  text="idTextCinta">
				<iconPath>assets/Families/Cubix Studio/Textures/Female/HeadbandFemaleMedieval.png</iconPath>
				<path>assets/Families/Cubix Studio/Textures/Female/HeadbandFemaleMedieval.png</path>
			</simpleTexture>
			<simpleTexture idPanelRef="accesoriesPanel" layer="1" idTexture="idLabiosCasual" default="true"  text="idTextLabiosCasual">
				<iconPath>assets/Families/Cubix Studio/Textures/Female/LipsFemaleCasual.png</iconPath>
				<path>assets/Families/Cubix Studio/Textures/Female/LipsFemaleCasual.png</path>
			</simpleTexture>
			<simpleTexture idPanelRef="accesoriesPanel" layer="1" idTexture="idLabiosMedieval" default="false"  text="idTextLabiosMedieval">
				<iconPath>assets/Families/Cubix Studio/Textures/Female/LipsFemaleMedieval.png</iconPath>
				<path>assets/Families/Cubix Studio/Textures/Female/LipsFemaleMedieval.png</path>
			</simpleTexture>
		</mainMeshTextures>
		<!--Bones-->
		<bones>
			<!-- Dar valores a los huesos, Los que hay son aleatorios -->
			<bone idControllerRef="head" defaultValue="0" minValue="-50" maxValue="100" boneName="Bip01 Head"/>
			<bone idControllerRef="arms" defaultValue="0" minValue="-50" maxValue="100" boneName="Bip01 L Clavicle"/>
			<bone idControllerRef="arms" defaultValue="0" minValue="-50" maxValue="100" boneName="Bip01 R Clavicle"/>
			<bone idControllerRef="hands" defaultValue="0" minValue="-50" maxValue="100" boneName="Bip01 L Hand"/>
			<bone idControllerRef="hands" defaultValue="0" minValue="-50" maxValue="100" boneName="Bip01 R Hand"/>
			<bone idControllerRef="legs" defaultValue="0" minValue="-50" maxValue="100" boneName="Bip01 L Calf"/>
			<bone idControllerRef="legs" defaultValue="0" minValue="-50" maxValue="100" boneName="Bip01 R Calf"/>
			<bone idControllerRef="feet" defaultValue="0" minValue="-50" maxValue="100" boneName="Bip01 L Foot"/>
			<bone idControllerRef="feet" defaultValue="0" minValue="-50" maxValue="100" boneName="Bip01 R Foot"/>
		</bones>		
		<!--Physical Builds-->
		<physicalBuilds>
			<physicalBuild label="idPhysicalBuildLabel1" idPanelRef="ScalePanel" idPhysicalBuild="idMediumBuilt">
				<escalation boneName="ALL" valueX="0.444" valueY="0.444" valueZ="0.444"/>
                                <escalation boneName="Bip01_Head" valueX="0.66" valueY="1.0" valueZ="1.0"/>
			</physicalBuild>
                        <physicalBuild label="idPhysicalBuildLabel2" idPanelRef="ScalePanel" idPhysicalBuild="idTall">
				<escalation boneName="ALL" valueX="0.488" valueY="0.555" valueZ="0.555"/>
                                <escalation boneName="Bip01_Head" valueX="0.66" valueY="1.0" valueZ="1.0"/>
			</physicalBuild>
                        <physicalBuild label="idPhysicalBuildLabel3" idPanelRef="ScalePanel" idPhysicalBuild="idSmall">
				<escalation boneName="ALL" valueX="0.4" valueY="0.333" valueZ="0.333"/>
                                <escalation boneName="Bip01_Head" valueX="0.66" valueY="1.0" valueZ="1.0"/>
			</physicalBuild>
		</physicalBuilds>
	</mainMesh>	
	<languagesPath>assets/Families/Cubix Studio/Locale/Female</languagesPath>
</model>

=== angeldelblanco/eCharacter/assets/Families/Cars/XML models/ferrari_f360.xml
<?xml version="1.0" encoding="UTF-8"?>
<model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../XSD/model.xsd">
	<mainMesh>
		<path>assets/Families/Cars/Models/Ferrari_f360/ferrari_f360.mesh.xml</path>
		<!--Transformations-->
		<transformation transformationType="scale" valueX="0.05" valueY="0.05" valueZ="0.05"/>
		 <transformation transformationType="translate" valueX="-2.5" valueY="-1.8" valueZ="0.0"></transformation>
		<transformation transformationType="rotate" valueX="0.0" valueY="240.0" valueZ="0.0"></transformation>
		<!--Textures-->
		<mainMeshTextures>
			<!-- bodyworkPanel textures-->
			<simpleTexture idPanelRef="bodyworkPanel" layer="0" default="false" idTexture="idPinturaVerde" text="idTextPinturaVerde">
				<iconPath>assets/Families/Cars/Textures/Ferrari_f360/f360_green.jpg</iconPath>
				<path>assets/Families/Cars/Textures/Ferrari_f360/f360_green.jpg</path>
			</simpleTexture>
			<simpleTexture idPanelRef="bodyworkPanel" layer="0" default="false" idTexture="idPinturaGris" text="idTextPinturaGris">
				<iconPath>assets/Families/Cars/Textures/Ferrari_f360/f360_grey.jpg</iconPath>
				<path>assets/Families/Cars/Textures/Ferrari_f360/f360_grey.jpg</path>
			</simpleTexture>
			<simpleTexture idPanelRef="bodyworkPanel" layer="0" default="true" idTexture="idPinturaRoja" text="idTextPinturaRoja">
				<iconPath>assets/Families/Cars/Textures/Ferrari_f360/f360_red.jpg</iconPath>
				<path>assets/Families/Cars/Textures/Ferrari_f360/f360_red.jpg</path>
			</simpleTexture>
			<simpleTexture idPanelRef="bodyworkPanel" layer="0" default="false" idTexture="idPinturaAmarilla" text="idTextPinturaAmarilla">
				<iconPath>assets/Families/Cars/Textures/Ferrari_f360/f360_yellow.jpg</iconPath>
				<path>assets/Families/Cars/Textures/Ferrari_f360/f360_yellow.jpg</path>
			</simpleTexture>
		</mainMeshTextures>
		<!--Bones-->
		<bones>
			<bone idControllerRef="torsoHeadArms" defaultValue="0" minValue="-50" maxValue="50" boneName=""/>
		</bones>
		<!--Physical Builds-->
		<physicalBuilds>
			<physicalBuild label="idPhysicalBuildLabel1" idPanelRef="ScalePanel" idPhysicalBuild="idMediumBuilt">
				<escalation boneName="ALL" valueX="1.0" valueY="1.0" valueZ="1.0"/>
			</physicalBuild>
		</physicalBuilds>
	</mainMesh>
	<languagesPath>assets/Families/Cars/Locale/Ferrari_f360</languagesPath>
</model>
